import type { School } from "./types";

export const NEIGHBORHOODS = [
  "العليا",
  "الملقا",
  "النرجس",
  "الياسمين",
] as const;

export const CURRICULA = [
  "سعودي",
  "أمريكي",
  "بريطاني",
  "IB",
  "كندي",
  "ثنائي اللغة",
] as const;

export const GENDERS = ["بنين", "بنات", "مختلط"] as const;
export const STAGES = ["روضة", "ابتدائي", "متوسط", "ثانوي"] as const;
export const TYPES = ["أهلية", "عالمية", "حكومية"] as const;

export const schools: School[] = [
  {
    id: "1",
    slug: "manarat-alolaya",
    name: "مدارس منارات العليا الأهلية",
    nameEn: "Manarat Al-Olaya Schools",
    neighborhood: "العليا",
    address: "شارع التحلية، حي العليا، الرياض",
    type: "أهلية",
    curriculum: "سعودي",
    gender: "مختلط",
    stages: ["روضة", "ابتدائي", "متوسط", "ثانوي"],
    feesMin: 18000,
    feesMax: 32000,
    phone: "+966112345678",
    website: "https://manarat-olaya.example.sa",
    coordinates: { lat: 24.6928, lng: 46.6837 },
    features: ["نقل مدرسي", "مختبرات علوم", "قاعات رياضية", "حضانة", "أنشطة لا صفية"],
    rating: 4.5,
    established: 1985,
    studentsCount: 1200,
    description:
      "من أعرق المدارس الأهلية في الرياض، تقدم منهجاً سعودياً معززاً باللغة الإنجليزية مع تركيز على الأنشطة العلمية والرياضية.",
  },
  {
    id: "2",
    slug: "british-international-school-riyadh",
    name: "المدرسة البريطانية العالمية بالرياض",
    nameEn: "British International School Riyadh",
    neighborhood: "الملقا",
    address: "طريق الملك عبدالعزيز، حي الملقا، الرياض",
    type: "عالمية",
    curriculum: "بريطاني",
    gender: "مختلط",
    stages: ["روضة", "ابتدائي", "متوسط", "ثانوي"],
    feesMin: 55000,
    feesMax: 95000,
    phone: "+966114567890",
    website: "https://bis-riyadh.example.com",
    coordinates: { lat: 24.7951, lng: 46.623 },
    features: [
      "منهج بريطاني (IGCSE/A-Levels)",
      "مسبح",
      "ملاعب عالمية",
      "مكتبة ضخمة",
      "مختبرات حديثة",
      "نقل",
    ],
    rating: 4.7,
    established: 1979,
    studentsCount: 1500,
    description:
      "مدرسة بريطانية معتمدة تقدم منهج Cambridge IGCSE وA-Levels، ببيئة دولية متعددة الثقافات وكادر تعليمي بريطاني.",
  },
  {
    id: "3",
    slug: "rowad-alkhaleej-narjs",
    name: "مدارس رواد الخليج الأهلية - النرجس",
    nameEn: "Rowad Al-Khaleej Schools",
    neighborhood: "النرجس",
    address: "حي النرجس، شمال الرياض",
    type: "أهلية",
    curriculum: "ثنائي اللغة",
    gender: "بنين",
    stages: ["روضة", "ابتدائي", "متوسط", "ثانوي"],
    feesMin: 22000,
    feesMax: 38000,
    phone: "+966112223344",
    website: "https://rowad.example.sa",
    coordinates: { lat: 24.8505, lng: 46.661 },
    features: ["برنامج ثنائي اللغة", "STEM", "روبوتيكس", "نقل", "حضانة"],
    rating: 4.4,
    established: 2003,
    studentsCount: 950,
    description:
      "مدارس رائدة في التعليم الثنائي اللغة (عربي/إنجليزي) مع تركيز قوي على STEM والبرمجة والروبوتيكس.",
  },
  {
    id: "4",
    slug: "american-international-yasmin",
    name: "المدرسة الأمريكية الدولية - الياسمين",
    nameEn: "American International School - Yasmin",
    neighborhood: "الياسمين",
    address: "حي الياسمين، شمال الرياض",
    type: "عالمية",
    curriculum: "أمريكي",
    gender: "مختلط",
    stages: ["روضة", "ابتدائي", "متوسط", "ثانوي"],
    feesMin: 48000,
    feesMax: 88000,
    phone: "+966115556677",
    website: "https://ais-yasmin.example.com",
    coordinates: { lat: 24.8428, lng: 46.6519 },
    features: [
      "منهج أمريكي (AdvancED)",
      "مكتبة",
      "مسرح",
      "ملاعب",
      "AP Courses",
      "نقل",
    ],
    rating: 4.6,
    established: 1995,
    studentsCount: 1100,
    description:
      "مدرسة أمريكية معتمدة من AdvancED تقدم منهج الولايات المتحدة الكامل مع برامج Advanced Placement للثانوية.",
  },
  {
    id: "5",
    slug: "alfaisaliah-girls-olaya",
    name: "مدارس الفيصلية الأهلية - بنات",
    neighborhood: "العليا",
    address: "شارع العروبة، حي العليا، الرياض",
    type: "أهلية",
    curriculum: "سعودي",
    gender: "بنات",
    stages: ["ابتدائي", "متوسط", "ثانوي"],
    feesMin: 16000,
    feesMax: 28000,
    phone: "+966112987654",
    coordinates: { lat: 24.6852, lng: 46.6745 },
    features: ["مختبرات", "أنشطة فنية", "رياضة", "نقل"],
    rating: 4.3,
    established: 1990,
    studentsCount: 800,
    description:
      "مدارس متخصصة لتعليم البنات بمنهج سعودي معزز، تركز على التميز الأكاديمي والأنشطة الفنية.",
  },
  {
    id: "6",
    slug: "kingdom-schools-malqa",
    name: "مدارس المملكة - الملقا",
    nameEn: "Kingdom Schools",
    neighborhood: "الملقا",
    address: "طريق الأمير محمد بن سلمان، الملقا",
    type: "أهلية",
    curriculum: "ثنائي اللغة",
    gender: "مختلط",
    stages: ["روضة", "ابتدائي", "متوسط", "ثانوي"],
    feesMin: 28000,
    feesMax: 52000,
    phone: "+966114440001",
    website: "https://kingdom.example.sa",
    coordinates: { lat: 24.79, lng: 46.6175 },
    features: [
      "منهج ثنائي اللغة",
      "مسبح",
      "ملاعب",
      "مسرح",
      "STEM Lab",
      "نقل",
      "تغذية",
    ],
    rating: 4.6,
    established: 2000,
    studentsCount: 1800,
    description:
      "من أكبر المجمعات التعليمية في الرياض، توفر منهجاً ثنائي اللغة ومرافق عالمية المستوى.",
  },
  {
    id: "7",
    slug: "ib-world-school-narjs",
    name: "مدرسة IB العالمية - النرجس",
    nameEn: "IB World School",
    neighborhood: "النرجس",
    address: "حي النرجس، الرياض",
    type: "عالمية",
    curriculum: "IB",
    gender: "مختلط",
    stages: ["روضة", "ابتدائي", "متوسط", "ثانوي"],
    feesMin: 60000,
    feesMax: 105000,
    phone: "+966112221122",
    website: "https://ib-narjs.example.com",
    coordinates: { lat: 24.8541, lng: 46.658 },
    features: [
      "برنامج IB كامل (PYP/MYP/DP)",
      "مكتبة دولية",
      "مختبرات حديثة",
      "ملاعب",
      "أنشطة ثقافية",
    ],
    rating: 4.8,
    established: 2008,
    studentsCount: 700,
    description:
      "مدرسة IB World معتمدة بالكامل، توفر برامج PYP وMYP وDiploma Programme للتأهيل للجامعات الدولية.",
  },
  {
    id: "8",
    slug: "alandalus-yasmin",
    name: "مدارس الأندلس الأهلية - الياسمين",
    neighborhood: "الياسمين",
    address: "حي الياسمين، الرياض",
    type: "أهلية",
    curriculum: "سعودي",
    gender: "بنين",
    stages: ["روضة", "ابتدائي", "متوسط"],
    feesMin: 14000,
    feesMax: 22000,
    phone: "+966115551111",
    coordinates: { lat: 24.8455, lng: 46.6488 },
    features: ["تحفيظ القرآن", "نقل", "أنشطة رياضية"],
    rating: 4.2,
    established: 2010,
    studentsCount: 550,
    description:
      "مدارس أهلية تركز على المنهج السعودي مع برنامج قوي لتحفيظ القرآن الكريم.",
  },
  {
    id: "9",
    slug: "canadian-bilingual-malqa",
    name: "المدرسة الكندية ثنائية اللغة",
    nameEn: "Canadian Bilingual School",
    neighborhood: "الملقا",
    address: "حي الملقا، شمال الرياض",
    type: "عالمية",
    curriculum: "كندي",
    gender: "مختلط",
    stages: ["روضة", "ابتدائي", "متوسط", "ثانوي"],
    feesMin: 42000,
    feesMax: 72000,
    phone: "+966114442233",
    website: "https://canadian.example.com",
    coordinates: { lat: 24.7988, lng: 46.6201 },
    features: ["منهج أونتاريو الكندي", "فرنسي اختياري", "ملاعب", "مكتبة", "نقل"],
    rating: 4.5,
    established: 2012,
    studentsCount: 850,
    description:
      "مدرسة كندية تقدم منهج أونتاريو OSSD بالكامل، مع خيار تعلم اللغة الفرنسية.",
  },
  {
    id: "10",
    slug: "dhahran-ahliyya-olaya",
    name: "مدارس الظهران الأهلية - فرع العليا",
    neighborhood: "العليا",
    address: "حي العليا، الرياض",
    type: "أهلية",
    curriculum: "ثنائي اللغة",
    gender: "بنات",
    stages: ["روضة", "ابتدائي", "متوسط", "ثانوي"],
    feesMin: 24000,
    feesMax: 42000,
    phone: "+966112334455",
    coordinates: { lat: 24.6951, lng: 46.6791 },
    features: ["ثنائي اللغة", "مختبرات علوم", "STEM", "أنشطة فنية", "نقل"],
    rating: 4.6,
    established: 1988,
    studentsCount: 1050,
    description:
      "فرع مدارس الظهران المرموقة، تقدم تعليماً ثنائي اللغة للبنات بجودة عالية.",
  },
  {
    id: "11",
    slug: "future-generations-yasmin",
    name: "مدارس أجيال المستقبل الأهلية",
    neighborhood: "الياسمين",
    address: "حي الياسمين، الرياض",
    type: "أهلية",
    curriculum: "سعودي",
    gender: "مختلط",
    stages: ["روضة", "ابتدائي"],
    feesMin: 12000,
    feesMax: 18000,
    phone: "+966115559900",
    coordinates: { lat: 24.8401, lng: 46.6562 },
    features: ["حضانة", "روضة", "أنشطة لا صفية", "نقل"],
    rating: 4.1,
    established: 2015,
    studentsCount: 320,
    description:
      "مدرسة جديدة نسبياً تركز على المراحل الأولى مع بيئة محفزة للأطفال.",
  },
  {
    id: "12",
    slug: "stem-academy-narjs",
    name: "أكاديمية STEM الأهلية",
    nameEn: "STEM Academy",
    neighborhood: "النرجس",
    address: "حي النرجس، الرياض",
    type: "أهلية",
    curriculum: "أمريكي",
    gender: "مختلط",
    stages: ["متوسط", "ثانوي"],
    feesMin: 35000,
    feesMax: 58000,
    phone: "+966112229988",
    website: "https://stem-academy.example.sa",
    coordinates: { lat: 24.8488, lng: 46.6635 },
    features: [
      "تركيز على العلوم والرياضيات",
      "روبوتيكس",
      "برمجة",
      "مختبرات هندسية",
      "AP Courses",
    ],
    rating: 4.7,
    established: 2017,
    studentsCount: 480,
    description:
      "أكاديمية متخصصة في تعليم STEM بمنهج أمريكي، تستهدف الطلاب الموهوبين علمياً.",
  },
  {
    id: "13",
    slug: "alroya-malqa-girls",
    name: "مدارس الرؤية الأهلية - بنات",
    neighborhood: "الملقا",
    address: "حي الملقا، شمال الرياض",
    type: "أهلية",
    curriculum: "سعودي",
    gender: "بنات",
    stages: ["روضة", "ابتدائي", "متوسط", "ثانوي"],
    feesMin: 17000,
    feesMax: 30000,
    phone: "+966114448822",
    coordinates: { lat: 24.7905, lng: 46.6298 },
    features: ["مختبرات", "قاعة رياضية", "أنشطة فنية", "نقل"],
    rating: 4.3,
    established: 2005,
    studentsCount: 720,
    description: "مدارس بنات بمنهج سعودي معزز وأنشطة متنوعة في بيئة آمنة.",
  },
  {
    id: "14",
    slug: "global-academy-yasmin",
    name: "الأكاديمية العالمية - الياسمين",
    nameEn: "Global Academy",
    neighborhood: "الياسمين",
    address: "حي الياسمين، الرياض",
    type: "عالمية",
    curriculum: "أمريكي",
    gender: "مختلط",
    stages: ["روضة", "ابتدائي", "متوسط"],
    feesMin: 38000,
    feesMax: 62000,
    phone: "+966115557722",
    website: "https://global-academy.example.com",
    coordinates: { lat: 24.8412, lng: 46.6541 },
    features: ["منهج أمريكي", "ESL", "ملاعب", "مختبرات", "نقل"],
    rating: 4.4,
    established: 2014,
    studentsCount: 600,
    description:
      "أكاديمية أمريكية للمراحل الأولى والمتوسطة، تركز على بناء الأساسيات بمنهج عالمي.",
  },
  {
    id: "15",
    slug: "alolaya-bilingual",
    name: "مدارس العليا ثنائية اللغة",
    neighborhood: "العليا",
    address: "حي العليا، الرياض",
    type: "أهلية",
    curriculum: "ثنائي اللغة",
    gender: "مختلط",
    stages: ["روضة", "ابتدائي", "متوسط", "ثانوي"],
    feesMin: 26000,
    feesMax: 45000,
    phone: "+966112221177",
    coordinates: { lat: 24.6981, lng: 46.6852 },
    features: ["ثنائي اللغة", "STEM", "أنشطة ثقافية", "نقل", "تغذية"],
    rating: 4.5,
    established: 1998,
    studentsCount: 1300,
    description:
      "مجمع تعليمي ثنائي اللغة في قلب العليا، يجمع بين القيم المحلية والمعايير الدولية.",
  },
  {
    id: "16",
    slug: "narjs-international",
    name: "مدارس النرجس العالمية",
    nameEn: "Narjs International",
    neighborhood: "النرجس",
    address: "حي النرجس، شمال الرياض",
    type: "عالمية",
    curriculum: "بريطاني",
    gender: "مختلط",
    stages: ["روضة", "ابتدائي", "متوسط", "ثانوي"],
    feesMin: 50000,
    feesMax: 85000,
    phone: "+966112226633",
    website: "https://narjs-intl.example.com",
    coordinates: { lat: 24.8523, lng: 46.6592 },
    features: [
      "IGCSE",
      "A-Levels",
      "مختبرات عالمية",
      "ملاعب",
      "مسرح",
      "نقل",
    ],
    rating: 4.6,
    established: 2010,
    studentsCount: 980,
    description:
      "مدرسة بريطانية حديثة في النرجس، توفر منهج كامبردج كاملاً وكادر بريطاني.",
  },
  {
    id: "17",
    slug: "tarbiya-namozajia-malqa",
    name: "مدارس التربية النموذجية - الملقا",
    neighborhood: "الملقا",
    address: "حي الملقا، الرياض",
    type: "أهلية",
    curriculum: "سعودي",
    gender: "بنين",
    stages: ["ابتدائي", "متوسط", "ثانوي"],
    feesMin: 15000,
    feesMax: 26000,
    phone: "+966114449911",
    coordinates: { lat: 24.7972, lng: 46.625 },
    features: ["تحفيظ القرآن", "أنشطة رياضية", "مختبرات", "نقل"],
    rating: 4.2,
    established: 1992,
    studentsCount: 870,
    description:
      "مدارس بنين بمنهج سعودي معزز ببرنامج قوي لتحفيظ القرآن وأنشطة رياضية متنوعة.",
  },
  {
    id: "18",
    slug: "tatweer-yasmin-girls",
    name: "مدارس التطوير الأهلية - بنات",
    neighborhood: "الياسمين",
    address: "حي الياسمين، الرياض",
    type: "أهلية",
    curriculum: "ثنائي اللغة",
    gender: "بنات",
    stages: ["روضة", "ابتدائي", "متوسط", "ثانوي"],
    feesMin: 20000,
    feesMax: 36000,
    phone: "+966115558844",
    website: "https://tatweer.example.sa",
    coordinates: { lat: 24.8465, lng: 46.6502 },
    features: ["ثنائي اللغة", "STEM", "أنشطة فنية", "مكتبة", "نقل"],
    rating: 4.5,
    established: 2007,
    studentsCount: 920,
    description:
      "مدارس بنات تجمع بين الأكاديميا القوية والأنشطة الإبداعية في بيئة محفزة.",
  },
];

export function getSchoolBySlug(slug: string): School | undefined {
  return schools.find((s) => s.slug === slug);
}

export function getAllSlugs(): string[] {
  return schools.map((s) => s.slug);
}

export interface SearchFilters {
  q?: string;
  neighborhood?: string;
  type?: string;
  curriculum?: string;
  gender?: string;
  stage?: string;
  feesMax?: number;
}

export function searchSchools(filters: SearchFilters): School[] {
  return schools.filter((s) => {
    if (filters.q) {
      const q = filters.q.trim().toLowerCase();
      const haystack = `${s.name} ${s.nameEn ?? ""} ${s.neighborhood} ${s.description}`.toLowerCase();
      if (!haystack.includes(q)) return false;
    }
    if (filters.neighborhood && s.neighborhood !== filters.neighborhood) return false;
    if (filters.type && s.type !== filters.type) return false;
    if (filters.curriculum && s.curriculum !== filters.curriculum) return false;
    if (filters.gender && s.gender !== filters.gender) return false;
    if (filters.stage && !s.stages.includes(filters.stage as never)) return false;
    if (filters.feesMax && s.feesMin > filters.feesMax) return false;
    return true;
  });
}

export function formatFees(min: number, max: number): string {
  const fmt = (n: number) => n.toLocaleString("ar-SA");
  return `${fmt(min)} - ${fmt(max)} ر.س`;
}
